### PR TITLE
Add Windows support with proper input handling:

### PR DESCRIPTION
**Pull request by konvar**
- Add conditional imports for Windows/Unix systems
- Use msvcrt for Windows input handling while keeping termios for Unix
- Fix input handling to properly support CTRL+Z on Windows

### CODE REVIEW

**Comment by leapingturtlefrog** [comment]
Don't know if it is from this pr, but this error occurs now ("list index out of range"):
image

The input works on though (Windows 11)!

**Comment by synth-mania** [comment]
I believe the issue is from PR #1
It's because of an error with the new multiple search providers support

**Comment by TheBlewish** [comment]
I Have now put hafeezhmha's windows compatible version into its own branch and hopefully fixed that issue which was due to an accidental merge please let me know if theres any other problems

**Comment by hafeezhmha** [comment]
@TheBlewish do you plan to merge the windows implementation?

**Pull request closed without merging**
