### PR TITLE
added openai support

### PR DESCRIPTION
**Pull request by benx13**

### CODE REVIEW

**Review by synth-mania — APPROVED** [review]
It could be argued that the way the LLM is configured could use a complete overhaul, but your implementation of openAI support follows the example TheBlewish set with their initial llama-cpp and ollama implementation, and seems like a well needed addition.

**Comment by TheBlewish** [comment]
so is this functional? I am busy with Uni exams today, but I will definitely check this out, I live in Australia so I am not ignoring y'all I think the time zones are just different, and Uni is a lot of work right now!

**Comment by synth-mania** [comment]
Yeah, being this was publicized on reddit I'm sure most of us are American. No problem

**Comment by noises1990** [comment]
Hey lads, would this work also for LMStudio localhost models?

**Comment by nightscape** [comment]
@noises1990 I'm currently using this fork with LM Studio:
https://github.com/NimbleAINinja/Automated-AI-Web-Researcher-Hosted/
I haven't tested this PR yet.

**Comment by synth-mania** [comment]
@noises1990 This PR would need some changes. As of now, it doesn't support setting a base URL other than openAI's own. The other fork @nightscape mentioned already supports connecting to an openAI API anywhere, including locally.

**Comment by synth-mania** [comment]
Awesome @benx13 that was some quick turnaround.

**Comment by benx13** [comment]
@synth-mania I've updated it to include the base url in the config/wrapper

**Comment by TheBlewish** [comment]
Hi there that has just been added thanks for your contribution!

**Comment by TheBlewish** [comment]
Please let me know if this version is better then the one currently merged

**Pull request closed without merging**
