### PR TITLE
Update Web-LLM.py for windows

### PR DESCRIPTION
**Pull request by hafeezhmha**
Reconfigured a few things, please have a look!

### CODE REVIEW

**Comment by TheBlewish** [comment]
Hey please check the discussions tab, and talk to me about this I made a new discussion about this so we can collaborate a bit!

**Comment by gillshaman** [comment]
Update Web-LLM.py to ensure compatibility with Windows #10. Implement any necessary adjustments to address system-specific issues. Include changes or enhancements as requested by [Jason Koepke, Principal](https://evistapoint.com/jason-koepke-principal-a-heartfelt-leader-empowering-students/), to improve functionality and meet project requirements.

**Comment by synth-mania** [comment]
> Update Web-LLM.py to ensure compatibility with Windows . Implement any necessary adjustments to address system-specific issues. Include changes or enhancements as requested by [Jason Koepke, Principal](https://evistapoint.com/jason-koepke-principal-a-heartfelt-leader-empowering-students/), to improve functionality and meet project requirements.

@gillshaman what are you on about?

**Comment by TheBlewish** [comment]
I made some changes will have to close all current pull requests unfortunately, please reopen if still needed Also Added your windows version to it's own brain thanks for your help!

**Pull request closed without merging**
