### PR TITLE
Update with NimbleAINinja's extra search providers, restructure project to hide internal files

### PR DESCRIPTION
**Pull request by synth-mania**
All the internal files are moved to a src/ folder, which is defined as a python module
A start.sh has been added which automatically handles creating, activating, and deactivating the python venv, as well as making sure all the requirements are installed and up to date.

### CODE REVIEW

**Comment by synth-mania** [comment]
@NimbleAINinja I'm also requesting a merge into the upstream fork.

**Comment by synth-mania** [comment]
Actually, hold that thought. I'm getting an error from the new search providers feature. I'll open a PR when this is resolved

**Comment by TheBlewish** [comment]
Thank you for your detailed contribution with the multiple search provider implementation. While I appreciate the effort and architectural design, I'm going to decline merging this for several reasons:

Simplicity and Accessibility

The current DuckDuckGo implementation is free and requires no API keys
Adding multiple providers would require users to obtain and manage various API keys
This would make the installation and setup process more complex for users


Core Philosophy

The project aims to be simple to set up and use
Current implementation works well for its intended purpose
DuckDuckGo provides sufficient search capabilities for our needs


Maintenance and Support

Multiple providers would mean maintaining multiple API integrations
Each provider has different rate limits, pricing, and terms of service
Would increase the complexity of error handling and documentation



I want to keep the barrier to entry low so anyone can clone and run the project without needing to sign up for multiple services or manage search API keys.
Thank you again for your contribution! While we won't be merging this particular change, I appreciate the thought and effort you put into it.

**Comment by synth-mania** [comment]
No problem, that's fair. I'm going to author a new PR with just the reorganization and start.sh, none of the extra APIs etc

**Comment by synth-mania** [comment]
@TheBlewish I'm confused? Apparently you already support multiple search providers?
https://github.com/TheBlewish/Automated-AI-Web-Researcher-Ollama/commit/a361b005c916bfdbe158098ddacb69bf0a7d403c
I must've missed this being added.
But why then are you saying that you want to avoid having multiple search providers?
I have to be missing something.

**Comment by synth-mania** [comment]
Wait I know what happened. Did you not realize that pr #1 included multiple search providers @TheBlewish ?

**Comment by TheBlewish** [comment]
Dammit, I didn't mean  to do that

**Comment by synth-mania** [comment]
I figured. The PR description didn't mention it, that was added well after the fact. I know everyone is busy, but the PR author has also been offline for days now as well, which is quite annoying as this has introduced a new issue. I'm sure you have seen the 'list index out of range' discussion. There's a bug where, when you don't have any API keys provided, it can't even use duckduck go now apparently.

It's okay, this is all pre-release anyways. We can fix this @TheBlewish

**Comment by synth-mania** [comment]
I suggest that you create a new branch right now called something like "feature/multi-search", then reset main back to before #1 was merged

**Comment by TheBlewish** [comment]
Thanks for your suggestions I already tried, but because I updated like a single file I will have to do this manually, god this will mess stuff up, but I guess it has to be done.

**Pull request closed without merging**
